### ISSUE TITLE
Google Maps not showing 

### ISSUE THREAD

**Issue by Karljoones** [addrum/CanIEatThis-Public-#2]
The Google map tab isn't showing any map or any information that should be on the map. Had this issue before, couldn't tell you how to solve it but it is an issue with the API key. The map is there as indicated by the Google logo but nothing else is loading.

**Comment by addrum** [comment]
@Karljoones Which device? Did you download it through the beta link?

**Comment by addrum** [comment]
@Karljoones could you also check if you've granted the app permissions in the app settings (if you're on Android M+)?

**Comment by Karljoones** [comment]
Sorry that was a terrible bug report there on my behalf:
Device: OnePlus One (A0001)
Android: 6.0.1

It was from the beta link, its up to date with the current Play version. Its got all the permissions it needs :)

**Comment by addrum** [comment]
@Karljoones no worries. It's better than nothing. I've just pushed an update (version 1.1.1) last night, could you let me know if the issue still persists? And attach a screenshot too. Thanks

**Comment by Karljoones** [comment]
Updated it before my second comment, issue still persists. Here is a screenshot:

![screenshot_20160517-154422](https://cloud.githubusercontent.com/assets/5596450/15326535/4e09f4f0-1c46-11e6-98c0-79c70a9e5fd7.png)

As you can see the mapview is showing, the map isnt loading. This usually means there is a problem with the API key, might be worth asking if anyone else is having this problem.

**Comment by addrum** [comment]
@Karljoones apologies for taking ages, this is a uni project so I got side tracked A LOT. What I didn't realise is that I forgot to add my release key as well as the debug key to the credentials list for the maps api hence why it was blank. I released an update yesterday which fixes this, please could you test and let me know if it works?

**Comment by addrum** [comment]
Closing as assumed fixed
